import json
import sys
from pathlib import Path

from google import genai
from google.genai import types
from google.genai import errors as genai_errors

from core.config import config
from core.settings import settings
from tools.parser_tools import (
    parse_swagger,
    parse_swagger_tool,
    parse_wsdl,
    parse_wsdl_tool,
)

client = genai.Client(api_key=settings.GEMINI_API_KEY)

planner_config = types.GenerateContentConfig(
    tools=[parse_swagger_tool, parse_wsdl_tool],
    tool_config=types.ToolConfig(
        function_calling_config=types.FunctionCallingConfig(
            mode=types.FunctionCallingConfigMode.ANY,
            allowed_function_names=["parse_swagger", "parse_wsdl"],
        )
    ),
    system_instruction=config.model.instruction.planner,
    temperature=0.0,  # We want the planner to be deterministic
)

worker_config = types.GenerateContentConfig(
    system_instruction=config.model.instruction.worker, temperature=0.2
)


def generate_endpoint_doc(endpoint_data: dict) -> str:
    print(f"Documenting: {endpoint_data['method']} {endpoint_data['path']}")
    prompt = f"Please document this specific endpoint:\n{json.dumps(endpoint_data, indent=2)}"

    try:
        response = client.models.generate_content(
            model=settings.MODEL_NAME, contents=prompt, config=worker_config
        )
        return response.text or ""
    except genai_errors.ServerError as exc:
        return f"## {endpoint_data['method']} {endpoint_data['path']}\n\nError generating documentation: {exc}"


def run_agent(raw_content: str) -> str:
    print("Planner: analyzing raw input to determine API type...")
    # use chat session to maintain conversation history
    chat = client.chats.create(model=settings.MODEL_NAME, config=planner_config)

    response = chat.send_message(f"Please parse this specification:\n\n{raw_content}")

    parsed_data = None

    # check if the planner decided to use a tool
    if response.function_calls:
        function_call = response.function_calls[0]  # Get the first function call
        tool_name = function_call.name
        print(f"Planner: calling tool -> {tool_name}")

        # Manually pass the raw content to the tool
        # The model selected the tool, but we provide the actual content
        if tool_name == "parse_swagger":
            print("System: parsing swagger...")
            parsed_data = parse_swagger(raw_content)
        elif tool_name == "parse_wsdl":
            print("System: parsing wsdl...")
            parsed_data = parse_wsdl(raw_content)
    else:
        return "Error: Planner Agent failed to identify the specification format and did not call a tool."

    if not parsed_data or "error" in parsed_data:
        error_msg = (
            parsed_data.get("error", "Unknown error")
            if parsed_data
            else "Unknown error"
        )
        return f"Error extracting API data: {error_msg}"

    # set up for worker loop
    api_name = parsed_data.get("api_name", "API")
    endpoints = parsed_data.get("endpoints", [])

    print(f"System: successfully extracted {len(endpoints)} endpoints.")
    print("System: Handing off to worker agent for docs generation...")

    documentation_chunks = [
        f"# {api_name} Documentation\n",
        "Auto-generated by API Doc Agent.\n---\n",
    ]

    for endpoint in endpoints:
        doc_chunk = generate_endpoint_doc(endpoint)
        documentation_chunks.append(doc_chunk)
        documentation_chunks.append("\n---\n")

    # assembly
    print("\nSystem: All endpoints documented! Assembling final output...")
    return "\n".join(documentation_chunks)


if __name__ == "__main__":
    try:
        # Resolve path relative to this script location
        swagger_path = Path(__file__).resolve().parent.parent / "data" / "swagger.json"
        with open(swagger_path, "r") as file:
            swagger_text = file.read()
    except FileNotFoundError:
        print(f"Error: Cannot find the json file at {swagger_path}")
        exit()

    # Run the agent and print the final Markdown
    final_markdown = run_agent(swagger_text)

    print("\n" + "=" * 50)
    print("FINAL DOCUMENTATION OUTPUT")
    print("=" * 50 + "\n")
    print(final_markdown)
