from datetime import datetime

from jinja2 import Template

# This is the master layout for your API documentation
MARKDOWN_TEMPLATE = """# {{ metadata.title | default('API') }} Documentation

## Overview
- **Base URL:** `{{ metadata.base_url }}`
- **API Version:** `{{ metadata.version | default('1.0') }}`

{% if metadata.description %}
{{ metadata.description }}
{% endif %}

## Authentication
{% if not security %}
This API does not require authentication.
{% else %}
{% for sec_name, sec_details in security.items() %}
**Method:** {{ sec_name }} ({{ sec_details.type }})
{% if sec_details.type == 'oauth2' %}
- **Flow:** `{{ sec_details.flow | default('implicit') }}`
- **Auth URL:** `{{ sec_details.authorizationUrl | default('N/A') }}`
- **Usage:** Acquire token from auth server, then send `Authorization: Bearer <token>`
{% elif sec_details.type == 'apiKey' %}
- **Included in:** `{{ sec_details.in | default('header') }}` as `{{ sec_details.name | default('X-API-Key') }}`
- **Usage:** `{{ sec_details.name }}: <your_api_key>`
{% elif sec_details.type == 'http' and sec_details.scheme == 'bearer' %}
- **Included in:** `header` as `Authorization`
- **Usage:** `Authorization: Bearer <your_jwt_token>`
{% else %}
- **Usage:** `Authorization: Basic <base64_encoded_credentials>`
{% endif %}

{% endfor %}
{% endif %}

---
## Table of Contents
{% for tag_name, endpoints in grouped_docs.items() %}
* **{{ tag_name }}**
{% for doc in endpoints %}
  * [{{ doc.method }} {{ doc.path }}](#{{ doc.method | lower }}-{{ doc.path | replace('/', '') | replace('{', '') | replace('}', '') | replace('_', '') | lower }})
{% endfor %}
{% endfor %}

---
## Endpoints

{% for tag_name, endpoints in grouped_docs.items() %}
### Category: {{ tag_name }}
---
{% for doc in endpoints %}
{{ doc.markdown }}

---
{% endfor %}
{% endfor %}

*Generated by API Doc Agent on {{ generated_at }}*
"""


def render_final_markdown(metadata: dict, grouped_docs: dict) -> str:
    """
    Takes the pure metadata and the LLM-generated endpoint chunks,
    and injects them into the Jinja2 template.
    """
    formatted_docs = {}
    for tag, eps in grouped_docs.items():
        clean_tag = tag.replace("_", " ").title()
        formatted_docs[clean_tag] = eps

    template = Template(MARKDOWN_TEMPLATE)

    return template.render(
        metadata=metadata,
        security=metadata.get("securityDefinitions", {}),
        grouped_docs=formatted_docs,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )
